[package]
name = "pyo3-antelope-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "antelope_rs"
# "cdylib" is necessary to produce a shared library for Python to import from.
#
# Downstream Rust code (including code in `bin/`, `examples/`, and `tests/`) will not be able
# to `use string_sum;` unless the "rlib" or "lib" crate type is also included, e.g.:
# crate-type = ["cdylib", "rlib"]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23.5", features = ["extension-module"]}
# antelope-client = { git = "https://github.com/telosnetwork/antelope-rs.git", rev = "6b42986f0621852a65946b5e508887f5dafab9c7" }
antelope-client = { path = "../antelope-rs/crates/antelope" }
chrono = "0.4.39"
pyo3-log = "0.12.1"
